routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'PublicController@showIndex')->name('welcome');

Auth::routes();

//Route::resource('/user/favorites', 'FavoriteController')->except('show', 'create', 'edit', 'update');
Route::get('/user/favorites/{recipe}', 'FavoriteController@index')->name('favorites.index');
Route::post('/user/favorites/{recipe}', 'FavoriteController@store')->name('favorites.store');
Route::delete('/user/favorites/{favorite}', 'FavoriteController@destroy')->name('favorites.destroy');


Route::get('/admin', 'HomeController@admin')->name('admin');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/gerechten', 'PublicController@gerechten')->name('gerechten');
Route::get('/gerechten/{recipe}', 'PublicController@show')->name('gerechten.show');
Route::get('/posts/showIndex', 'PublicController@showPosts')->name('posts.showIndex');
Route::get('/post/{post}', 'PublicController@showPost')->name('post.detail');
Route::resource('/post/{post}/comments', 'CommentController')->except('index', 'create', 'show', 'edit', 'update');
Route::post('/searchRecipe', 'PublicController@searchRecipe')->name('search');
Route::post('/searchPost', 'PublicController@searchPost')->name('posts.search');
Route::get('/top5', 'PublicController@top5')->name('top5');
Route::get('/about', 'PublicController@about')->name('about');

Route::resource('/admin/recipes', 'RecipeController')->except('show');
Route::resource('/admin/recipes/{recipe}/ingredients', 'IngredientController')->except('index', 'show');
Route::resource('/admin/products', 'ProductController')->except('show');
Route::resource('/admin/units', 'UnitController')->except('show');
Route::resource('/admin/recipes/{recipe}/steps', 'StepController')->except('index','show');
Route::resource('/admin/posts', 'PostController');
Route::resource('/admin/categories', 'CategoryController')->except('show');
Route::resource('/contacts', 'ContactController')->except('show', 'edit', 'update');

resources/views/inc/alerts.blade.php
{{--@if(session('status'))--}}
    {{--<div class="alert alert-success mb-3">--}}
        {{--{{ session('status') }}--}}
    {{--</div>--}}
{{--@endif--}}

@if(session('success'))
    <div class="alert alert-success mb-3">
        {{ session('success') }}
    </div>
@endif

@if(session('failed'))
    <div class="alert alert-danger mb-3">
        {{ session('failed') }}
    </div>
@endif

resources/views/inc/footer.blade.php
<script src="{{ asset('js/theme.js') }}"></script>

</body>
</html>

resources/views/inc/header.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>My site</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

    <!-- Styles -->
    @if(Request::is('admin') || Request::is('admin/') || Request::is('admin/*'))
        <link href="{{ asset('css/theme.css') }}" rel="stylesheet">
    @else
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @endif

</head>
<body>

resources/views/inc/navbar.blade.php
<nav class="navbar navbar-expand-md">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url('/') }}">
            Home
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('posts.showIndex') }}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('top5') }}">Top 5 </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('about') }}">Over ons</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('contacts.create') }}">Contact</a>
                </li>
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                    <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>
                            @if (Auth::check() && Auth::user()->hasrole('admin'))
                                <a class="dropdown-item" href="/admin">Back to Admin</a>
                                @else <a class="dropdown-item" href="/home">Terug naar Profile</a>
                            @endif


                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/inc/navbarAdmin.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-light navbar-laravel">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url('/') }}">
            Admin
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                    <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>
                            <a class="dropdown-item" href="{{ route('welcome') }}">Back to Home</a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/inc/navbarUser.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-light navbar-laravel">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url('/') }}">
            Home
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                    <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>
                            @if (Auth::check() && Auth::user()->hasrole('admin'))
                                <a class="dropdown-item" href="/admin">Back to Admin</a>
                            @else <a class="dropdown-item" href="/">Terug naar Home</a>
                            @endif
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/inc/sidebar.blade.php
<div class="col-md-4 col-lg-2 mt-3">
    <div class="card">
        <div class="card-header"><i class="fas fa-utensils"></i> Recepten</div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><a href="{{ route('recipes.index') }}" class="card-link text-muted" style="color: #000">Alle recepten</a></li>
                <li class="list-group-item"><a href="{{ route('products.index') }}" class="card-link text-muted" style="color: #000">Alle product</a></li>
                <li class="list-group-item"><a href="{{ route('units.index') }}" class="card-link text-muted" style="color: #000">Alle eenheden</a></li>
                <li class="list-group-item"><a href="{{ route('recipes.create') }}" class="card-link text-muted" style="color: #000">Nieuw recept</a></li>
                <li class="list-group-item"><a href="{{ route('products.create') }}" class="card-link text-muted" style="color: #000">Nieuw product</a></li>
                <li class="list-group-item"><a href="{{ route('units.create') }}" class="card-link text-muted" style="color: #000">Nieuw eenheid</a></li>
            </ul>
    </div>
    <br>
    <div class="card">
        <div class="card-header"><i class="fab fa-blogger-b"></i> Posts</div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><a href="{{ route('posts.index') }}" class="card-link text-muted">Alle posts</a></li>
            <li class="list-group-item"><a href="{{ route('categories.index') }}" class="card-link text-muted">Alle categorie&euml;n</a></li>
            <li class="list-group-item"><a href="{{ route('posts.create') }}" class="card-link text-muted">Nieuwe post</a></li>
            <li class="list-group-item"><a href="{{ route('categories.create') }}" class="card-link text-muted">Nieuwe categorie</a></li>
        </ul>
    </div>
    <br>
    <div class="card">
        <div class="card-header"><i class="fas fa-at"></i> Contacts</div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><a href="{{ route('contacts.index') }}" class="card-link text-muted">Alle vragen</a></li>
            </ul>
        </div>
    </div>