routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'PublicController@showIndex')->name('welcome');

Auth::routes();

//Route::resource('/user/favorites', 'FavoriteController')->except('show', 'create', 'edit', 'update');
Route::get('/user/favorites/{recipe}', 'FavoriteController@index')->name('favorites.index');
Route::post('/user/favorites/{recipe}', 'FavoriteController@store')->name('favorites.store');
Route::delete('/user/favorites/{favorite}', 'FavoriteController@destroy')->name('favorites.destroy');


Route::get('/admin', 'HomeController@admin')->name('admin');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/gerechten', 'PublicController@gerechten')->name('gerechten');
Route::get('/gerechten/{recipe}', 'PublicController@show')->name('gerechten.show');
Route::get('/posts/showIndex', 'PublicController@showPosts')->name('posts.showIndex');
Route::get('/post/{post}', 'PublicController@showPost')->name('post.detail');
Route::resource('/post/{post}/comments', 'CommentController')->except('index', 'create', 'show', 'edit', 'update');
Route::post('/searchRecipe', 'PublicController@searchRecipe')->name('search');
Route::post('/searchPost', 'PublicController@searchPost')->name('posts.search');
Route::get('/top5', 'PublicController@top5')->name('top5');
Route::get('/about', 'PublicController@about')->name('about');

Route::resource('/admin/recipes', 'RecipeController')->except('show');
Route::resource('/admin/recipes/{recipe}/ingredients', 'IngredientController')->except('index', 'show');
Route::resource('/admin/products', 'ProductController')->except('show');
Route::resource('/admin/units', 'UnitController')->except('show');
Route::resource('/admin/recipes/{recipe}/steps', 'StepController')->except('index','show');
Route::resource('/admin/posts', 'PostController');
Route::resource('/admin/categories', 'CategoryController')->except('show');
Route::resource('/contacts', 'ContactController')->except('show', 'edit', 'update');

app/Recipe.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Recipe extends Model
{
    public $directory = "/images/";

    protected $fillable = ['name', 'desc', 'sort', 'time', 'number'];

    public function photos(){

        return $this->hasOne('App\Photo');
    }

    public function ingredients(){

        return $this->hasMany('App\Ingredient');
    }

    public function steps(){

        return $this->hasMany('App\Step');
    }


}

app/Http/Controllers/RecipeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreRecipeRequest;
use App\Ingredient;
use App\Photo;
use App\Product;
use App\Recipe;
use App\Step;
use App\Unit;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class RecipeController extends Controller
{
    public function __construct()
    {
        $this->middleware('authAdmin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $recipes = Recipe::orderBy('id', 'desc')->paginate(8);

        Return view('admin/recipes/index', compact('recipes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $request->user()->authorizeRoles('admin');
        return view('admin/recipes/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRecipeRequest $request)
    {
        $request->user()->authorizeRoles('admin');

        $recipe = new Recipe;
        $photo = new Photo;

        $recipe->name = $request->input('name');
        $recipe->desc = $request->input('desc');
        $recipe->sort = $request->input('sort');
        $recipe->time = $request->input('time');
        $recipe->number = $request->input('number');

        if ($file = $request->file('file')){

            $name = $file->getClientOriginalName();
            $file->move('images', $name);
            $photo->path = $name;
        }

        $recipe->save();
        $recipe->photos()->save($photo);

        return redirect()->route('recipes.edit', $recipe->id)->with('success', 'Inserted successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Recipe $recipe
     * @return \Illuminate\Http\Response
     */
    public function edit(Recipe $recipe, Request $request)
    {
        $request->user()->authorizeRoles('admin');

        $quantities = Ingredient::where('recipe_id', '=', $recipe->id)->paginate(6);
        $products = Product::all();
        $units = Unit::all();
        $steps = $recipe->steps;
        return view('admin/recipes/edit', compact('recipe', 'steps', 'quantities', 'products', 'units', 'paginates'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->user()->authorizeRoles('admin');
        $recipe = Recipe::findOrFail($id);

        $recipe->update($request->only('name', 'desc', 'sort', 'time', 'number'));

        return redirect()->route('recipes.index')->with('success', 'Updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, Request $request)
    {
        $request->user()->authorizeRoles('admin');
        $recipe = Recipe::findOrFail($id);
        $recipe->photos()->delete();

        foreach($recipe->ingredients as $ingredient){
            foreach($ingredient->units as $unit){
                $ingredient->units()->detach($unit->id);
            }
            foreach($ingredient->products as $product){
                $ingredient->products()->detach($product->id);
            }
        }

        $recipe->delete();

        return redirect()->route('recipes.index');
    }


}

resources/views/admin/recipes/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="col-md-10 mt-3">

    {{--Create Recipe--}}
    <form action="{{ route('recipes.store') }}" method="post" enctype="multipart/form-data">
        {{ csrf_field() }}
        <div class="card">
            <h6 class="card-header text-muted">Nieuw recept</h6>
            <div class="card-body">
                <h6 class="card-title">Recepten naam</h6>
                <div class="form-group">
                <input type="text" class="form-control" name="name"><br>
                @if($errors->has('name'))
                    <span class="text-danger">Naam is verplicht.</span>
                @endif
                </div>
                <div class="form-group">
                    <input type="file" name="file">
                    @if($errors->has('file'))
                        <span class="text-danger">Foto uploaden is verplicht.</span>
                    @endif
                </div>
                <h6 class="card-title">Beschrijving</h6>
                <div class="form-group">
                <textarea name="desc" id="desc" cols="30" rows="5" class="form-control"></textarea>
                    @if($errors->has('desc'))
                        <span class="text-danger">Veld is verplicht.</span>
                    @endif
                </div>
                <h6 class="card-title">Categorie</h6>
                <div class="form-group">
                    <select name="sort" id="sort" class="form-control" >
                        <option value="ontbijt">ontbijt</option>
                        <option value="lunch">Lunch</option>
                        <option value="salade">Salade</option>
                        <option value="voorgerecht">Voorgerecht</option>
                        <option value="hoofdgerecht">Hoofdgerecht</option>
                        <option value="Bijgerecht">Bijgerecht</option>
                        <option value="dessert">Dessert</option>
                        <option value="gebak">Gebak & Taarten</option>
                    </select>
                    @if($errors->has('sort'))
                        <span class="text-danger">Veld is verplicht.</span>
                    @endif
                </div>
                <h6 class="card-title">Bereidings tijd</h6>
                <div class="form-group">
                    <input type="text" class="form-control" name="time">
                    @if($errors->has('time'))
                        <span class="text-danger">Veld is verplicht.</span>
                    @endif
                </div>
                <h6 class="card-title">Aantal Personen</h6>
                <div class="form-group">
                    <input type="text" class="form-control" name="number">
                    @if($errors->has('number'))
                        <span class="text-danger">Veld is verplicht.</span>
                    @endif
                </div>
                <button class="btn btn-outline-primary btn-sm" type="submit" name="submit">Create</button>
            </div>
        </div>
    </form>
    {{--End create Recipe--}}
</div>


    @endsection

resources/views/admin/recipes/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-md-10 mt-3">
        {{--Edit Recipe--}}
        <form action="{{ route('recipes.update', $recipe->id) }}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            @method('PUT')
            <div class="card">
                <h6 class="card-header text-muted">Edit recept</h6>
                <div class="card-body">
                    <h6 class="card-title">Recepten naam</h6>
                    <div class="form-group">
                        <input type="text" class="form-control" name="name" value="{{ $recipe->name }}">
                        @if($errors->has('name'))
                            <span class="text-danger">{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                    <h6 class="card-title">Beschrijving</h6>
                    <div class="form-group">
                        <textarea name="desc" id="desc" cols="30" rows="5" class="form-control">{{ $recipe->desc }}</textarea>
                    </div>
                    <h6 class="card-title">Soort</h6>
                    <div class="form-group">
                        <select name="sort" id="sort" class="form-control">
                            <option value="ontbijt" {{$recipe->sort === 'ontbijt' ? 'Selected' : '' }}>Ontbijt</option>
                            <option value="lunch" {{$recipe->sort === 'lunch' ? 'Selected' : '' }}>Lunch</option>
                            <option value="salade" {{$recipe->sort === 'salade' ? 'Selected' : '' }}>Salade</option>
                            <option value="voorgerecht" {{$recipe->sort === 'voorgerecht' ? 'Selected' : '' }}>Voorgerecht</option>
                            <option value="hoofdgerecht" {{$recipe->sort === 'hoofdgerecht' ? 'Selected' : '' }}>Hoofdgerecht</option>
                            <option value="bijgerecht" {{$recipe->sort === 'bijgerecht' ? 'Selected' : '' }}>Bijgerecht</option>
                            <option value="dessert" {{$recipe->sort === 'dessert' ? 'Selected' : '' }}>Dessert</option>
                            <option value="gebak" {{$recipe->sort === 'gebak' ? 'Selected' : '' }}>Gebak & Taarten</option>
                        </select>
                    </div>
                    <h6 class="card-title">Bereidings tijd</h6>
                    <div class="form-group">
                        <input type="text" class="form-control" name="time" value="{{ $recipe->time }}">
                    </div>
                    <h6 class="card-title">Aantal Personen</h6>
                    <div class="form-group">
                        <input type="text" class="form-control" name="number" value="{{ $recipe->number }}">
                    </div>

                    <button class="btn btn-outline-primary btn-sm" type="submit" name="submit">Update</button>
                </div>
            </div>
        </form>
       {{-- End edit Recipe--}}


        <div class="card mt-3">
            {{--Add new Product--}}
            <h6 class="card-header text-muted">Ingredi&euml;nten</h6>
            <div class="card-body">
                <table class="table table-sm table-hover">
                    <thead>
                    <tr>
                        <th>Naam</th>
                        <th>Hoeveelheid</th>
                        <th>Eenheid</th>
                        <th scope="col" width="120">Controls</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($quantities as $quantity)
                    <tr>
                        <td>
                            {{ $quantity->products->first()['name'] }}
                        </td>
                        <td>
                            {{ floatval($quantity->quantity) }}
                        </td>
                        <td>
                            {{ $quantity->units->first()['units'] }}
                        </td>
                        <td>
                            <form action="{{ route('ingredients.destroy', [$recipe, $quantity]) }}" method="post">
                                {{ csrf_field() }}
                                @method('DELETE')
                                <a href="{{ route('ingredients.edit', [$recipe, $quantity]) }}" class="btn btn-outline-secondary btn-sm">Edit</a>
                                <button class="btn btn-outline-danger btn-sm">Delete</button>
                            </form>
                        </td>
                    </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $quantities->links() }}
                <div class="text-right">
                    <a href="{{ route('ingredients.create', $recipe->id) }}" class="btn btn-sm btn-outline-secondary">Ingredi&euml;nt toevoegen</a>
                </div>
            </div>
            {{--End new Product--}}
        </div>



        <div class="card mt-3">
            {{--Add new Steps--}}
            <h6 class="card-header text-muted">Stappen</h6>
            <div class="card-body">
                <table class="table table-sm table-hover">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Stappen</th>
                        <th scope="col" width="120">Controls</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach( $steps as $step)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ str_limit($step->desc) }}</td>
                        <td>
                            <form action="{{ route('steps.destroy', [$recipe->id, $step->id]) }}" method="POST">
                                {{ csrf_field() }}
                                @method('DELETE')
                                <a href="{{ route('steps.edit', [$recipe->id, $step->id]) }}" class="btn btn-outline-secondary btn-sm">Edit</a>
                                <button class="btn btn-outline-danger btn-sm">Delete</button>
                            </form>
                        </td>
                    </tr>
                        @endforeach
                    </tbody>
                </table>
                <div class="text-right">
                    <a href="{{ route('steps.create', $recipe->id) }}" class="btn btn-sm btn-outline-secondary">Stap toevoegen</a>
                </div>
            </div>
        </div>
        {{--End new Steps--}}
    </div>


@endsection

resources/views/admin/recipes/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="col-md-10 mt-3">
        @include('inc.alerts')

        {{--Table recipes--}}
        <div class="card">
            <h6 class="card-header text-muted">Alle Recepten</h6>
            <div class="card-body">
                <table class="table table-sm table-hover">
                    <thead>
                    <tr>
                        <th scope="col" width="30">Id</th>
                        <th>Naam</th>
                        <th scope="col" width="150">Foto</th>
                        <th scope="col" width="120">Controls</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($recipes as $recipe)
                        <tr>
                            <td>{{ $recipe->id }}</td>
                            <td>{{ $recipe->name }}</td>
                            <td><img src="/images/{{ isset($recipe->photos->path) ? $recipe->photos->path : ''  }}" alt="image" class="card-img" style="width: 80px;"></td>
                            <td>
                                <form action="{{ route('recipes.destroy', $recipe->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <a href="{{ route('recipes.edit', $recipe->id) }}" class="btn btn-outline-secondary btn-sm">Edit</a>
                                    <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                {{ $recipes->links() }}
            </div>
        </div>
        {{--End table Recipes--}}
    </div>

    @endsection

resources/views/admin/recipes/show.blade.php
@extends('layouts.app')

@include('inc.navbar')
@section('content')
<div class="col mt-3">
    {{--Show Recipe--}}
        <div class="card">
            <div class="card-body">
                <div class="img"></div>
                <img src="/images/{{ isset($recipe->photos->path) ? $recipe->photos->path : ''  }}" alt="image" class="show_img">
                <p></p>
                <h2 class="card-title" style="min-height: 50px;">{{ $recipe->name }}</h2>
                <p class="card-text" style="min-height: 30px;">{{ $recipe->desc }}</p>
                <br>
                <p><i class="far fa-clock"></i> {{ $recipe->time }}</p>
                <p><i class="fas fa-user"></i> {{ $recipe->number }} personen</p>
                <br>
                <h5 class="card-title">Ingredi&euml;nten</h5>
                <ul>
                    @foreach($recipe->ingredients as $ingredient)
                        <li><p>{{ floatval($ingredient->quantity) }} {{ $ingredient->units->first()['units'] }} {{ $ingredient->products->first()['name'] }}</p></li>
                    @endforeach
                </ul>
                <br>
                <h5 class="card-title">Bereiding</h5>
                @foreach($recipe->steps as $step)
                <p class="card-text">{{ $step->desc }}</p>
                @endforeach
                <a href="{{ route('welcome') }}" class="btn btn-outline-info btn-sm">Terug naar Home</a>
            </div>
        </div>
    {{--End show Recipe--}}
</div>
    @endsection