routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'PublicController@showIndex')->name('welcome');

Auth::routes();

//Route::resource('/user/favorites', 'FavoriteController')->except('show', 'create', 'edit', 'update');
Route::get('/user/favorites/{recipe}', 'FavoriteController@index')->name('favorites.index');
Route::post('/user/favorites/{recipe}', 'FavoriteController@store')->name('favorites.store');
Route::delete('/user/favorites/{favorite}', 'FavoriteController@destroy')->name('favorites.destroy');


Route::get('/admin', 'HomeController@admin')->name('admin');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/gerechten', 'PublicController@gerechten')->name('gerechten');
Route::get('/gerechten/{recipe}', 'PublicController@show')->name('gerechten.show');
Route::get('/posts/showIndex', 'PublicController@showPosts')->name('posts.showIndex');
Route::get('/post/{post}', 'PublicController@showPost')->name('post.detail');
Route::resource('/post/{post}/comments', 'CommentController')->except('index', 'create', 'show', 'edit', 'update');
Route::post('/searchRecipe', 'PublicController@searchRecipe')->name('search');
Route::post('/searchPost', 'PublicController@searchPost')->name('posts.search');
Route::get('/top5', 'PublicController@top5')->name('top5');
Route::get('/about', 'PublicController@about')->name('about');

Route::resource('/admin/recipes', 'RecipeController')->except('show');
Route::resource('/admin/recipes/{recipe}/ingredients', 'IngredientController')->except('index', 'show');
Route::resource('/admin/products', 'ProductController')->except('show');
Route::resource('/admin/units', 'UnitController')->except('show');
Route::resource('/admin/recipes/{recipe}/steps', 'StepController')->except('index','show');
Route::resource('/admin/posts', 'PostController');
Route::resource('/admin/categories', 'CategoryController')->except('show');
Route::resource('/contacts', 'ContactController')->except('show', 'edit', 'update');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['name'];

    public function ingredients(){

        return $this->belongsToMany('App\Ingredient');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StorePostRequest;
use App\Http\Requests\StoreProductRequest;
use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $products = Product::orderBy('id', 'desc')->paginate(15);
        return view('admin/products/index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin/products/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProductRequest $request)
    {
            $product = new Product;
            $product->name = $request->input('name');
            $product->save();

        return redirect()->route('products.index')->with('success', 'Inserted successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::findOrFail($id);

        return view('admin/products/edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::findOrFail($id);
        $product->update($request->only('name'));

        return redirect()->route('products.index')->with('success', 'Updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        $product->delete();

        return redirect()->route('products.index')->with('success', 'Deleted successfully');
    }
}

resources/views/admin/products/create.blade.php
@extends('layouts.admin')

@section('content')

    <div class="col-md-10 mt-3">

        {{--Create Product--}}
        <form action="{{ route('products.store') }}" method="POST">
            {{ csrf_field() }}
            <div class="card">
                <h6 class="card-header text-muted">Nieuw product</h6>
                <div class="card-body">
                    <h6 class="card-title">Ingredi&euml;nten naam</h6>
                    <div class="form-group">
                        <input name="name" type="text" id="name" class="form-control">
                        @if($errors->has('name'))
                            <span class="text-danger">Naam is verplicht.</span>
                        @endif
                    </div>
                    <button class="btn btn-outline-primary btn-sm" type="submit" name="submit">Create</button>
                </div>
            </div>
        </form>
        {{--End create Product--}}
    </div>
    @endsection

resources/views/admin/products/edit.blade.php
@extends('layouts.admin')

@section('content')

    <div class="col-md-10 mt-3">

        {{--Edit Product--}}
        <form action="{{ route('products.update', $product->id) }}" method="POST">
            {{ csrf_field() }}
             @method('PUT')
            <div class="card">
                <h6 class="card-header text-muted">Edit product</h6>
                <div class="card-body">
                    <h6 class="card-title">Ingredi&euml;nten naam</h6>
                    <div class="form-group">

                        <input name="name" type="text" id="name" class="form-control" value="{{ old('name') != null ? old('name') : (isset($product->name) ? $product->name : '') }}">
                        @if($errors->has('name'))
                            <span class="text-danger">{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                    <button class="btn btn-outline-primary btn-sm" type="submit" name="submit">Edit</button>
                </div>
            </div>
        </form>
        {{--End create Product--}}
    </div>
@endsection

resources/views/admin/products/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="col-md-10 mt-3">
        @include('inc.alerts')

        {{--Table Prodcuts--}}
        <div class="card">
            <h6 class="card-header text-muted">Alle Producten</h6>
            <div class="card-body">
                <table class="table table-sm table-hover">
                    <thead>
                    <tr>
                        <th scope="col" width="30">#</th>
                        <th scope="col">Product Naam</th>
                        <th scope="col" width="120">Controls</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach( $products as $product)
                            <tr>
                                <td> {{ $loop->iteration }} </td>
                                <td> {{ isset($product->name) ? $product->name : '' }} </td>
                                <td>
                                    <form action="{{ route('products.destroy', $product->id) }}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <a href="{{ route('products.edit', $product->id) }}" class="btn btn-outline-secondary btn-sm">Edit</a>
                                        <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $products->links() }}
            </div>
        </div>
        {{--End table Products--}}
    </div>
@endsection