routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'PublicController@showIndex')->name('welcome');

Auth::routes();

//Route::resource('/user/favorites', 'FavoriteController')->except('show', 'create', 'edit', 'update');
Route::get('/user/favorites/{recipe}', 'FavoriteController@index')->name('favorites.index');
Route::post('/user/favorites/{recipe}', 'FavoriteController@store')->name('favorites.store');
Route::delete('/user/favorites/{favorite}', 'FavoriteController@destroy')->name('favorites.destroy');


Route::get('/admin', 'HomeController@admin')->name('admin');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/gerechten', 'PublicController@gerechten')->name('gerechten');
Route::get('/gerechten/{recipe}', 'PublicController@show')->name('gerechten.show');
Route::get('/posts/showIndex', 'PublicController@showPosts')->name('posts.showIndex');
Route::get('/post/{post}', 'PublicController@showPost')->name('post.detail');
Route::resource('/post/{post}/comments', 'CommentController')->except('index', 'create', 'show', 'edit', 'update');
Route::post('/searchRecipe', 'PublicController@searchRecipe')->name('search');
Route::post('/searchPost', 'PublicController@searchPost')->name('posts.search');
Route::get('/top5', 'PublicController@top5')->name('top5');
Route::get('/about', 'PublicController@about')->name('about');

Route::resource('/admin/recipes', 'RecipeController')->except('show');
Route::resource('/admin/recipes/{recipe}/ingredients', 'IngredientController')->except('index', 'show');
Route::resource('/admin/products', 'ProductController')->except('show');
Route::resource('/admin/units', 'UnitController')->except('show');
Route::resource('/admin/recipes/{recipe}/steps', 'StepController')->except('index','show');
Route::resource('/admin/posts', 'PostController');
Route::resource('/admin/categories', 'CategoryController')->except('show');
Route::resource('/contacts', 'ContactController')->except('show', 'edit', 'update');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name'];

    public function posts(){

        return $this->belongsTo('App\Post');
    }
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['title', 'content'];

    public function photos(){

        return $this->hasOne('App\Photo');
    }

    public function categories(){

        return $this->hasMany('App\Category');
    }

    public function comments(){

        return $this->hasMany('App\Comment');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\StoreCategoryRequest;
use App\Post;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     */
    public function index()
    {

        $categories = Category::all();
        return view( 'admin/posts/categories/index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/posts/categories/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return void
     */
    public function store(StoreCategoryRequest $request)
    {
        $categorie = new Category;
        $categorie->name = $request->input('name');

        $categorie->save();


        return redirect()->route('categories.index')->with('success', 'Inserted successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categorie = Category::findOrFail($id);

        return view('admin/posts/categories/edit', compact('categorie'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $categorie = Category::findOrFail($id);
        $categorie->name = $request->name;
        $categorie->update();

        return redirect()->route('categories.index')->with('success', 'Updated successfully');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $categorie = Category::findOrFail($id);
        $categorie->delete();

        return redirect()->route('categories.index')->with('success', 'Deleted successfully');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\StorePostRequest;
use App\Post;
use App\Photo;
use Illuminate\Http\Request;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('authAdmin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();
        $categories = Category::all();

        return view('admin/posts/index', compact('posts', 'categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin/posts/create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePostRequest $request)
    {
        $post = new Post;
        $photo = new Photo;

        $post->title = $request->input('title');
        $post->body = $request->input('body');

        if ($file = $request->file('file')) {

            $name = $file->getClientOriginalName();
            $file->move('images', $name);
            $photo->path = $name;
        }

        $post->category_id = $request->category_id;

        $post->save();
        $post->photos()->save($photo);

        return redirect()->route('posts.index')->with('success', 'Inserted successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::findOrFail($id);
        $categorie = Category::all();


        return view('admin/posts/show', compact('post', 'categorie'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        $categories = Category::all();

        return view('admin/posts/edit', compact('post', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post = Post::findOrFail($id);
        $post->title = $request->input('title');
        $post->body = $request->input('body');
        $post->category_id = $request->category_id;
        $post->update();

        return redirect()->route('posts.index')->with('success', 'Updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::findOrFail($id);
        $post->photos()->delete();
        $post->delete();

        return redirect()->route('posts.index')->with('success', 'Deleted successfully');
    }
}

resources/views/admin/posts/categories/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-md-10 mt-3">

        {{--Create Categories--}}
        <form action="{{ route('categories.store') }}" method="post">
            {{ csrf_field() }}
            <div class="card">
                <h6 class="card-header text-muted">Nieuwe categorie</h6>
                <div class="card-body">
                    <div class="card-title">Categorie naam</div>
                    <div class="form-group">
                        <input type="text" name="name" class="form-control">
                        @if($errors->has('name'))
                            <span class="text-danger">Naam is verplicht!</span>
                            @endif
                    </div>
                    <button class="btn btn-outline-primary btn-sm" type="submit" name="submit">Create</button>
                </div>
            </div>
        </form>

        {{--End create Categories--}}
    </div>
@endsection

resources/views/admin/posts/categories/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-md-10 mt-3">

        {{--Edit Categories--}}
        <form action="{{ route('categories.update', $categorie->id) }}" method="post">
            {{ csrf_field() }}
            @method('PUT')
            <div class="card">
                <h6 class="card-header text-muted">Edit categorie</h6>
                <div class="card-body">
                    <div class="card-title">Categorie naam</div>
                    <div class="form-group">
                        <input type="text" name="name" class="form-control" value="{{ old('name', $categorie->name)  }}">
                    </div>
                    <button class="btn btn-outline-primary btn-sm" type="submit" name="submit">Update</button>
                </div>
            </div>
        </form>
        {{--End edit Categories--}}
    </div>
@endsection

resources/views/admin/posts/categories/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-md-10 mt-3">
        @include('inc.alerts')

        {{--Table Categories--}}
        <div class="card">
            <h6 class="card-header text-muted">Alle categorie&euml;n</h6>
            <div class="card-body">
                <table class="table table-sm table-hover">
                    <thead>
                    <tr>
                        <th scope="col" width="30">Id</th>
                        <th>Categorie naam</th>
                        <th scope="col" width="120">Controls</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($categories as $categorie)
                    <tr>
                        <td>{{ $categorie->id }}</td>
                        <td>{{ $categorie->name }}</td>
                        <td>
                            <form action="{{ route('categories.destroy', $categorie->id) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <a href="{{ route('categories.edit', $categorie->id) }}" class="btn btn-outline-secondary btn-sm">Edit</a>
                                <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                            </form>
                        </td>
                    </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        {{--End table Categories--}}
    </div>
@endsection